spring: # test profile
  datasource:
    url: "jdbc:h2:mem:Code2CV"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true # SQL 포맷팅
        highlight_sql: true
logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
    SQL: debug