spring: # test profile
  datasource:
    url: "jdbc:h2:mem:Code2CV"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true # SQL 포맷팅
        highlight_sql: true
logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
    SQL: debug
jwt:
  secret: 4099a46b-39db-4860-a61b-2ae76ea24c43
  access-token-expire-time: 1800000 # 30 minutes
  refresh-token-expire-time: 2592000000 # 30 days